platform :ios, '13.0'

target 'PokeList' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PokeList
  pod 'RealmSwift'
  pod 'SnapKit', '~> 5.0.0'

end