# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'PokeList' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PokeList
  pod 'SwiftLint'

  target 'PokeListTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PokeListUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
